version: "3"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_secret
      MYSQL_DATABASE: instagram
      MYSQL_USER: capybara
      MYSQL_PASSWORD: my_secret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - REDIS_PASSWORD=redis_password
  #   volumes:
  #     - redis_data:/data
  #   command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'

volumes:
  # redis_data:
  #   driver: local
  mysql_data:
    driver: local
